version: '3.7'
services:
  backend:
    container_name: bhw_backend
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Time@12345
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "bhw"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
  phpmyadmin:
    container_name: bhw_phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 3001:80
    environment:
      PMA_HOST: backend
    restart: unless-stopped
  frontend:
    container_name: bhw-app
    build: .
    ports:
      - 80:80
    depends_on: 
      - backend
volumes:
  db-data:

